/**
 * Compass Config Loader
 * Loads project-specific config from compass.config.js if it exists
 */
import fs from 'fs';
import path from 'path';

export async function loadProjectConfig(projectPath) {
  const configPath = path.join(projectPath, 'compass.config.js');
  if (!fs.existsSync(configPath)) return null;
  
  try {
    // Dynamic import for ESM
    const config = await import(`file://${configPath}?t=${Date.now()}`);
    return config.default || config;
  } catch (e) {
    console.error(`Failed to load compass.config.js: ${e.message}`);
    return null;
  }
}

export function saveProjectConfig(projectPath, config) {
  const configPath = path.join(projectPath, 'compass.config.js');
  const projectName = path.basename(projectPath);
  const content = `/**
 * Compass Configuration for ${projectName}
 * Generated by AI Horizon
 */
export default ${JSON.stringify(config, null, 2)};
`;
  
  try {
    fs.writeFileSync(configPath, content, 'utf-8');
    return true;
  } catch (e) {
    console.error(`Failed to save compass.config.js: ${e.message}`);
    return false;
  }
}
